ability to restrict watched resources by namespace
TykTechnologies/tyk-operator pull request #164
Opened 2020-11-13 23:38 UTC by asoorm

2020-11-14 15:06 UTC, gernest requested changes
I haven't tested yet , just left a comment

So I have following namespaces

```
NAME                  STATUS   AGE
cert-manager          Active   2d22h
default               Active   2d22h
kube-node-lease       Active   2d22h
kube-public           Active   2d22h
kube-system           Active   2d22h
local-path-storage    Active   2d22h
tyk-operator-system   Active   2d22h
tykce-control-plane   Active   2d22h
```

Creating apidef in `default` namespace I get this error inside the controller

```
... "httpbin.164767f486037709" is forbidden: User "system:serviceaccount:tyk-operator-system:default" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
```

Does this PR address this ? What was the previous behaviour?

2020-11-14 15:12 UTC, asoorm commented
> I haven't tested yet , just left a comment
> 
> So I have following namespaces
> 
> ```
> NAME                  STATUS   AGE
> cert-manager          Active   2d22h
> default               Active   2d22h
> kube-node-lease       Active   2d22h
> kube-public           Active   2d22h
> kube-system           Active   2d22h
> local-path-storage    Active   2d22h
> tyk-operator-system   Active   2d22h
> tykce-control-plane   Active   2d22h
> ```
> 
> Creating apidef in `default` namespace I get this error inside the controller
> 
> ```
> ... "httpbin.164767f486037709" is forbidden: User "system:serviceaccount:tyk-operator-system:default" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
> ```
> 
> Does this PR address this ? What was the previous behaviour?

I think your issue is different. Check master:

https://github.com/TykTechnologies/tyk-operator/blob/master/Makefile#L66-L67

2020-11-14 15:31 UTC, gernest approved these changes

2020-11-15 17:23 UTC, gernest commented on main.go
> +	const watchNamespaceEnvVar = "WATCH_NAMESPACE"
@asoorm  This is only used within the function call, used only once, and can't be changed without looking at the function call (Meaning not meant to easy refactoring). The doc comment looks like a global exported symbol to me.

In this case `os.LookupEnv( "WATCH_NAMESPACE")`  should be fine

Did I miss something?

2020-11-17 10:25 UTC, merged