[TT-5320] - Support different namespaces for SubGraph
TykTechnologies/tyk-operator pull request #458
Opened 2022-05-17 12:46 UTC by buraksekili

## Description
This PR adds a support for subgraphs to be created in different namespaces; and then joint together by a single supergraph.

## Related Issue

## Motivation and Context

The current implementation of federation support on the operator does not allow users to use subgraphs in different namespaces than supergraph. So, if the supergraph is in the `default` namespace, Operator was not able to find referenced subgraphs which are not in `default` namespace.

This PR aims to support use of subgraphs in different namespaces in the SuperGraph CRD.
For example, let's say you have `Users` SubGraph in `users-ns` namespace.
This SubGraph must be accessible for SuperGraph as well. So that we can give reference of it in SuperGraph CRD declaration.

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] Make sure you are updating [CHANGELOG.md](../CHANGELOG.md) based on your changes.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `gofmt -s -w .`
  - [x] `go vet ./...`
  - [x] `golangci-lint run`

2022-05-17 13:34 UTC, asoorm requested changes

2022-05-17 13:34 UTC, asoorm commented on helm/crds/crds.yaml
>                subgraphs_refs:
this should be `subgraph_refs`

2022-05-17 13:34 UTC, asoorm commented on api/v1alpha1/supergraph_types.go
> +	SubgraphsRefs []SubGraphReference `json:"subgraphs_refs"`
Don't we already have a more generic container type for this which is used elsewhere? e.g. something like `type NamespacedName struct {...`?

2022-05-24 12:08 UTC, buraksekili commented
closed in favor of #466

2022-05-24 12:08 UTC, closed without merging