Prevent reading k8s config while running snapshot tool
TykTechnologies/tyk-operator pull request #569
Opened 2023-02-20 19:14 UTC by buraksekili

## Description
Previously, snapshot tool was reading the k8s config even though it does not require any specific k8s API functionality. So, in order for users to use the snapshot tool, they need to have a running k8s environment; so that the program could read k8s config.

This PR updates the main file of tyk-operator. While running in snapshot mode, it does not do any k8s specific operation.

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] Make sure you are updating [CHANGELOG.md](https://github.com/TykTechnologies/tyk-operator/blob/master/CHANGELOG.md) based on your changes.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] If you've changed API models, please update CRDs.
  - [ ] `make manifests`
  - [ ] `make helm`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `gofmt -s -w .`
  - [ ] `go vet ./...`
  - [ ] `golangci-lint run`

2023-02-21 08:55 UTC, andrei-tyk approved these changes

2023-02-21 09:22 UTC, letzya requested changes

2023-02-21 09:22 UTC, letzya commented on CHANGELOG.md
> +- Prevent reading k8s config while using snapshot.
```suggestion
- Prevent reading k8s config while using `operator snapshot` as a CLI command.
```

2023-03-03 11:23 UTC, letzya requested changes

2023-03-03 11:23 UTC, letzya commented on CHANGELOG.md
> +- Prevent reading k8s config while using `operator snapshot` as a CLI command.
```suggestion
- Prevent reading Kubernetes config while using `operator snapshot` as a CLI command (this means you don't need to have a running Kubernetes cluster when running `operator snapshot`).
```

2023-03-03 11:29 UTC, letzya approved these changes

2023-03-06 07:47 UTC, andrei-tyk approved these changes

2023-03-14 07:23 UTC, merged