[TT-11505 ] OAS controller reconciliation logic optimisations
TykTechnologies/tyk-operator pull request #718
Opened 2024-06-26 13:25 UTC by buraksekili

## Description

- Update delete reconciliation logic to handle deletion of non-existing APIs.
- Optimise reconcilition of OAS APIs - prevent sending redundant PUT requests to Tyk which may be costly.

## Related Issue

https://tyktech.atlassian.net/browse/TT-11505

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] Make sure you are updating [CHANGELOG.md](https://github.com/TykTechnologies/tyk-operator/blob/master/CHANGELOG.md) based on your changes.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] If you've changed API models, please update CRDs.
  - [ ] `make manifests`
  - [ ] `make helm`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `gofmt -s -w .`
  - [ ] `go vet ./...`
  - [ ] `golangci-lint run`

2024-07-01 08:03 UTC, komalsukhani requested changes

2024-07-01 08:14 UTC, buraksekili commented on api/v1alpha1/tykoasapidefinition_types.go
> +	LatestTykSpecHash string `json:"latestTykSpecHash,omitempty"`
Actually, I used LatestTykSpecHash to make controllers consistent with each other as the api_definition controller also uses the same name. Do you think it is not relevant to the intention of the field? if so, I can rename it.

2024-07-01 08:15 UTC, buraksekili commented on controllers/tykoasapidefinition_controller.go
> +	cmHash := calculateHash(tykOASDoc)
You are right, i will move `cmHash` initialization right after fetching ConfigMap.

2024-07-01 08:36 UTC, buraksekili commented on controllers/tykoasapidefinition_controller.go
> +		if isSame(tykOASCrd.Status.LatestTykSpecHash, oasApiDefOnTyk) &&
updated accordingly in 1eefac239ad6a28b1e1cdc1cab68f40e39f99d96. Could you please take a look?

2024-07-01 10:22 UTC, komalsukhani commented on api/v1alpha1/tykoasapidefinition_types.go
> +	LatestTykSpecHash string `json:"latestTykSpecHash,omitempty"`
When I read it for the first time I thought it's CRD Spec Hash. But later I realized it's not.
That's why I added this comment. 
It's okay to keep it as is. It was just first impression.

2024-07-01 10:24 UTC, komalsukhani approved these changes

2024-07-03 07:58 UTC, bojantyk commented
LGTM , @buraksekili  we can proceed with merging this PR. 
Thanks,

2024-07-03 07:58 UTC, bojantyk approved these changes

2024-07-04 09:04 UTC, merged